version: "3.8"

services:
    mysql-db:
        image: mysql:8
        container_name: mysql-db
        environment:
            MYSQL_DATABASE: { DB_DATABASE }
            MYSQL_USER: { DB_USERNAME }
            MYSQL_PASSWORD: { DB_PASSWORD }
            MYSQL_ROOT_PASSWORD: { DB_PASSWORD }
        ports:
            - "3306:3306"
        networks:
            - laravel-net
        volumes:
            - mysql-data:/var/lib/mysql

    php-app:
        image: demo/laravel:0.1
        container_name: php-app
        ports:
            - "8001:8000"
        networks:
            - laravel-net
        depends_on:
            - mysql-db
        volumes:
            - .:/var/www/html
        command: php artisan serve --host=0.0.0.0 --port=8000

networks:
    laravel-net:
        driver: bridge

volumes:
    mysql-data:
